name: Playwright Check
env:
  CI: true
  FORCE_COLOR: 1
  NODE_OPTIONS: --max_old_space_size=4096
on: workflow_dispatch
jobs:
  setup:
    name: Playwright Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16.13
        uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - name: Project package install
        run: npm install
      - name: Install Playwright
        run: npx playwright install --with-deps